export const CHAR_ALL_REQUEST = 'CHAR_ALL_REQUEST';
export const CHAR_ALL_SUCCESS = 'CHAR_ALL_SUCCESS';
export const CHAR_ALL_ERROR = 'CHAR_ALL_ERROR';

export const SINGLE_CHAR_REQUEST = 'SINGLE_CHAR_REQUEST';
export const SINGLE_CHAR_SUCCESS = 'SINGLE_CHAR_SUCCESS';
export const SINGLE_CHAR_ERROR = 'SINGLE_CHAR_ERROR';